### PR TITLE
Feature/library

### PR DESCRIPTION
**Pull request by Maryjanee**
Following the completion of the project, we request approval to merge changes from the feature/library branch into the develop branch.
The following functions have been implemented as stated in the requirements for the project.
- A modal with a form to add a new book
- A table to display all the added books
- A button to toggle read status of the book 
- A button to delete a specific book

### CODE REVIEW

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
## Status: Changes requested 🔴 

### Hello @Maryjanee and @ldelbel 👋 

### Your project is looking so good, and it's doing almost everything it's supposed to do 👏 It really looks gorgeous, very nice job 🥇 

### Please follow my improvement suggestions below:

- [x] Why don't you add a Live Link to your README file for quick access? You can do it with Githack or Netlify very quickly.

- [x] Add the `.vscode` folder to your `.gitignore` file, we don't need it online, right?

- [x] The user should be able to mark the book as read or not when creating one, not only when it's already created ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/new_book_button_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

- [x] **(OPTIONAL)** This is a personal opinion, but I would change the book reading status from "false" and "true" to "Read" and "Unread". It looks more descriptive this way from my point of view.

- [ ] **(OPTIONAL)** You could change your function declaration to ES6 Arrow functions.

- [x] **(OPTIONAL)** You could use some kind of data persistence in your project, like the [localStorage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API), just so the books I add are still there even if I refresh the page.

## Summary

- Your project is very professional, README and PR description are beautifully structured 💯 
- Your code is impeccable, so easy to read and understand, what a pleasure 😄 
- There are only some little details to fix before moving on 🚀 

Kindly make the requested changes and submit for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @Maryjanee and @ldelbel, great job on this project :+1: You did a great job fixing most of the comments made by the previous TSE :+1: However, I encountered a bug when I tried to run the application. Kindly check the comments below:
- The `add book` button is not displaying the modal for the form. It returns `Uncaught ReferenceError: displayModal is not defined` as in the screenshot below
vb
- Let us use ES6 syntax. Use `const functionName = () => {}` instead of `function functionName = {}`

Kindly submit another code review once this is resolved :smile: 
_Happy coding_ :woman_technologist: :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### You have done well so far :clap: However, you have a failing eslint errors in the pull request branch - feature/library. Kindly install all the required dependencies, configure and run command `npx eslint .` [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/javascript)
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Review by rOluochKe — APPROVED** [review]
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit for another code review. Good luck with the next one.
- Happy coding!

**Pull request merged**
